# Generated by Django 5.2.8 on 2026-06-24 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255, unique=True)),
                ('total_launches', models.IntegerField(default=0)),
                ('successful_launches', models.IntegerField(default=0)),
                ('failed_launches', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(null=True)),
                ('avg_status_changes', models.FloatField(null=True)),
                ('most_common_orbit', models.CharField(blank=True, max_length=100, null=True)),
                ('most_common_mission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='ID of the launch in the external API.', max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(blank=True, help_text='Launch provider (e.g. SpaceX, NASA, ESA).', max_length=255, null=True)),
                ('mission_name', models.CharField(blank=True, help_text='Mission name if available.', max_length=255, null=True)),
                ('mission_description', models.TextField(blank=True, help_text='Short description of the mission.', null=True)),
                ('net', models.DateTimeField(help_text='No Earlier Than (NET) datetime of the launch.')),
                ('window_start', models.DateTimeField(blank=True, help_text='Launch window start datetime.', null=True)),
                ('window_end', models.DateTimeField(blank=True, help_text='Launch window end datetime.', null=True)),
                ('pad_name', models.CharField(blank=True, help_text='Launch pad name.', max_length=255, null=True)),
                ('location_name', models.CharField(blank=True, help_text='Launch site / location name.', max_length=255, null=True)),
                ('rocket_name', models.CharField(blank=True, help_text='Rocket or launch vehicle name.', max_length=255, null=True)),
                ('rocket_family', models.CharField(blank=True, max_length=100, null=True)),
                ('orbit', models.CharField(blank=True, max_length=100, null=True)),
                ('mission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('launch_success', models.BooleanField(null=True)),
                ('image_url', models.URLField(blank=True, help_text='Main image URL for this launch.', null=True)),
                ('info_url', models.URLField(blank=True, help_text='More information about this launch.', null=True)),
                ('webcast_url', models.URLField(blank=True, help_text='Webcast or livestream URL.', null=True)),
                ('status', models.CharField(blank=True, help_text='Launch status (e.g. Go, TBD, Success).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when this record was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Datetime when this record was last updated.')),
            ],
            options={
                'ordering': ['net'],
            },
        ),
        migrations.CreateModel(
            name='RocketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_family', models.CharField(max_length=100, unique=True)),
                ('total_launches', models.IntegerField(default=0)),
                ('successful_launches', models.IntegerField(default=0)),
                ('failed_launches', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(null=True)),
                ('avg_status_changes', models.FloatField(null=True)),
                ('most_common_orbit', models.CharField(blank=True, max_length=100, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=100, null=True)),
                ('new_status', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.launch')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_agency', models.CharField(blank=True, help_text='Optional preferred space agency.', max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowedLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True, help_text='Datetime when the user started following this launch.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_launches', to=settings.AUTH_USER_MODEL)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='core.launch')),
            ],
            options={
                'verbose_name': 'Followed launch',
                'verbose_name_plural': 'Followed launches',
                'unique_together': {('user', 'launch')},
            },
        ),
    ]
