# Generated by Django 5.2.8 on 2026-06-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='launch_success',
            field=models.BooleanField(blank=True, help_text='Whether the launch succeeded. Null for upcoming launches.', null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='mission_type',
            field=models.CharField(blank=True, help_text='Mission type (e.g. Communications, Earth Science)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='orbit',
            field=models.CharField(blank=True, help_text='Target orbit (e.g. LEO, GEO, SSO)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='rocket_family',
            field=models.CharField(blank=True, help_text='Rocket family (e.g. Falcon, Soyuz)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LaunchStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, max_length=100, null=True)),
                ('new_status', models.CharField(max_length=100)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='core.launch')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
