# Generated by Django 5.2.8 on 2026-06-23

from django.db import migrations, models


def copy_launch_external_ids(apps, schema_editor):
    FollowedLaunch = apps.get_model("core", "FollowedLaunch")

    for followed_launch in FollowedLaunch.objects.select_related("launch"):
        launch_external_id = ""
        if followed_launch.launch_id:
            try:
                launch_external_id = followed_launch.launch.external_id
            except Exception:
                launch_external_id = str(followed_launch.launch_id)

        followed_launch.launch_external_id = launch_external_id
        followed_launch.save(update_fields=["launch_external_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="followedlaunch",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="followedlaunch",
            name="launch_external_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(
            copy_launch_external_ids,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="followedlaunch",
            name="launch",
        ),
        migrations.AlterUniqueTogether(
            name="followedlaunch",
            unique_together={("user", "launch_external_id")},
        ),
        migrations.DeleteModel(
            name="Launch",
        ),
        migrations.RunSQL(
            sql=[
                "DROP TABLE IF EXISTS core_launchstatushistory",
                "DROP TABLE IF EXISTS core_agencystats",
                "DROP TABLE IF EXISTS core_rocketstats",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
