# Generated by Django 5.2.8 on 2026-06-24 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('launch_data_snapshot', models.TextField(help_text='Snapshot of launch data used to generate this briefing')),
                ('launch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='briefing', to='core.launch')),
            ],
        ),
    ]
