# Generated by Django 5.2.8 on 2026-06-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_launch_launch_success_launch_mission_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=255, unique=True)),
                ('total_launches', models.IntegerField(default=0)),
                ('successful_launches', models.IntegerField(default=0)),
                ('failed_launches', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(blank=True, help_text='Percentage 0-100', null=True)),
                ('avg_status_changes', models.FloatField(blank=True, help_text='Average number of status changes per launch', null=True)),
                ('most_common_orbit', models.CharField(blank=True, max_length=100, null=True)),
                ('most_common_mission_type', models.CharField(blank=True, max_length=100, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RocketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocket_family', models.CharField(max_length=100, unique=True)),
                ('total_launches', models.IntegerField(default=0)),
                ('successful_launches', models.IntegerField(default=0)),
                ('failed_launches', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(blank=True, null=True)),
                ('avg_status_changes', models.FloatField(blank=True, null=True)),
                ('most_common_orbit', models.CharField(blank=True, max_length=100, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
